### ISSUE TITLE
No module named clj

### ISSUE THREAD

**Issue by aj07mm** [tony-landis/datomic-py#2]
```
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datomic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/datomic/__init__.py", line 29, in <module>
    from datomic import (
  File "/usr/local/lib/python2.7/dist-packages/datomic/datomic.py", line 13, in <module>
    from clj import dumps, loads
ImportError: No module named clj
```

**Comment by kabumbc** [comment]
Somente news about this fix?

**Comment by mardukbp** [comment]
See the PR #1. 

```diff
- from clj import dumps, loads
+ from edn_format import dumps, loads
```
